const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUtEb2hNb2loMWFuWVBFcXVmRmNlQml0WU0xazJZUS9kWDd4bWJVKytFST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUHZNb0lJMmVsR1FzRlN2d1pWSzdDWUVPem5Gd25CWm03a1lnZEFWU3duST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnSWx1alowa3g1TURWSlJKWjVNcTNMZm5GdURqd0tkclZjL3UvK2xRMGtJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtaDU0Y0xCM1BvaXhmZDk3cnhQNHpoZ3BWcVRkQ2k1Y0RCbFJKeGl3clZrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdLQy9yNWtPQ0FIcVNLNGMzTXdGN0RDSlRQSUJqVXlVL1NjWDV6N2lka3M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9xMXJrT2dlWkVOME9ZM2VCK3NFUURyUFF3MytlSXZLbDllUFo2S2NWaU09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEtDeEg3S0U5ek55Qmk1NEIzS3l3TGFPM2NpTDdpVVNPMEZUZktkdXFYTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSDNIcVZKdW1DR1lzYTNmVWptN3FIS0thK3JFWlNBb2E2Wk5VZTY2eURscz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBFMDZCMDNMY2xnUnBHYXpXRll1ZXMvemMxYlBrZ24wVTVlYlJWYkMxclNJWWZzNlc3T3VmUkR0Q0JwSEJ6YWVzeWFqQ1BEZmJ6WjcraGxRTGhLd2lnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTIyLCJhZHZTZWNyZXRLZXkiOiJBUWxlb0FiSlpIN29yM2xBRC9WcCtCZDV3M24wVi96SmxOWFZOYjY5VkJjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiIwU2hFN183S1FtLTMyXzRVNTU3dXFnIiwicGhvbmVJZCI6IjE4NGUxMmJjLTI3MTAtNDI5OS04MjQ3LWY4OWQwOGYyM2FiYyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5NFVBSSszMDFIdFdWYk13SUFCS0pGbGlOM1U9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaFQyVnM5RFdxN1F2cEZDMlpoS1VhdlBnQXJnPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjNHNFFLUE5KIiwibWUiOnsiaWQiOiIyNTQ3OTM5MDgwMzg6NEBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS2Y1cGQ4SEVKK0dsNzRHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5Ijoiay8xK2labEYwMW5yL21zR0xZTEIrTDRvZk80U2pQN2dYK1NaTEJka0ZBTT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiZ240ZVhnbzY4QzBUaEdtNGdVK2RnRnNjSDNuZEl4bjBEUjVPK2w2R2RkbGpYZWROUGVNQmt5cVFGSEs0YnZuZHVrV080NTJESEdrTy9yWlp3QWVWQ1E9PSIsImRldmljZVNpZ25hdHVyZSI6IlhyVzJuU0xPSm5rbGdpVm0vQkJQTGFWU1NmanVySm5JYW9oSTdVNm5mS3kxRUYrcmNIOUN1RnpsZ0JmREtNdE5mdENBWWw1eEpMb1pyYk5WRDNGcmp3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzkzOTA4MDM4OjRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWlA5Zm9tWlJkTlo2LzVyQmkyQ3dmaStLSHp1RW96KzRGL2ttU3dYWkJRRCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0MTAxMzgwNH0=
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
